// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Proto_1
REST API Backend for Cornell Notes - Prototype


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json
    - text/plain

swagger:meta
*/
package restapi
