package db

//InsertSampleData ... stores sample data for DB
var InsertSampleData = map[string]string{
	"User 1":          "INSERT INTO users (id, user_name, email, password) VALUES('324ddsf3', 'Steve', 'S@dfs.com' ,'testing');",
	"User 2":          "INSERT INTO users (id, user_name, email, password) VALUES('sfs34344', 'Emma Watson', 'ewat@ymail.co.uk' ,'password');",
	"User 3":          "INSERT INTO users (id, user_name, email, password) VALUES('sfsdf443', 'Ted Bundy', 'todiefor@mail.com', 'password');",
	"Folder 1":        "INSERT INTO folders (id, title, date_created, date_edited) VALUES('werwr433', 'Machine Learning', '2020-01-03', '2020-01-03');",
	"Folder 2":        "INSERT INTO folders (id, title, date_created, date_edited) VALUES('434rsfg4', 'Cryptography', '2020-01-03', '2020-01-03');",
	"Folder 1 User 1": "INSERT INTO folder_users (folder_id, user_id) VALUES('werwr433', '324ddsf3' );",
	"Folder 2 User 1": "INSERT INTO folder_users (folder_id, user_id) VALUES('434rsfg4', '324ddsf3' );",
	"folder_item1":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('werwr433', '12313c1ccc3223cd', 'Note' );",
	"folder_item2":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('434rsfg4', '14234254533334cd',  'Note');",
	"folder_item3":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('434rsfg4', 'ewrwerewercccvv333',  'CornellNote');",
	"folder_item4":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('434rsfg4', '23rresfdf434r34r34',  'CornellNote');",
	"Note 1":          "INSERT INTO notes (id, title) VALUES('12313c1ccc3223cd', 'Spyder' );",
	"Note 2":          "INSERT INTO notes (id, title) VALUES('14234254533334cd', 'Ciphers' );",
	"Note 1 User 1":   "INSERT INTO note_users (note_id, user_id ) VALUES('12313c1ccc3223cd', '324ddsf3' );",
	"Note 2 User 1":   "INSERT INTO note_users (note_id, user_id ) VALUES('14234254533334cd', '324ddsf3' );",
	"CornellNote 1":   "INSERT INTO cornell_notes (id, title) VALUES('ewrwerewercccvv333', 'Veniger Ciphers' );",
	"CornellNote 2":   "INSERT INTO cornell_notes (id, title) VALUES('23rresfdf434r34r34', 'Casear Ciphers' );",
	"CN Cue 1":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('werrtetgvcxd', '23rresfdf434r34r34',  'What is the Vigenere Cipher', 'This scheme is based on using 26 Caeser ciphers with differing shifts of 0 - 25' );",
	"CN Cue 2":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('fgderrtreer', 'ewrwerewercccvv333',  'What type of cipher is it', 'A polyalphabetical  substitution cipher');",
	"CN Cue 3":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('fdgdgdf343434', 'ewrwerewercccvv333',  'More sample cuesss', 'that have more sample answers' );",
	"CN Cue 4":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('fdgdfge454', 'ewrwerewercccvv333',  'CorMore sample cuesssnellNote', 'efv44 that eeee more sample answers' );",
	"CN Cue 5":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('2435ttgfsf', '23rresfdf434r34r34',  'More sample cuesss', '3efdgvthat have more sample answers' );",
	"CN Cue 6":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('3544dgdgdd', '23rresfdf434r34r34',  'More another on', 'dddf5 that have more sample answers' );",
	"CN 1 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('ewrwerewercccvv333', '324ddsf3' );",
	"CN 2 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('23rresfdf434r34r34', '324ddsf3' );",
	"Tag 1 User 1":    "INSERT INTO tags (id, title, user_id, color) VALUES('325er3f573', 'Definitions', '324ddsf3', 'red' );",
	"Tag 2 User 1":    "INSERT INTO tags (id, title, user_id, color) VALUES('wtrferjsdg', 'Security', '324ddsf3', 'orange' );",
	"Tag 3 User 1":    "INSERT INTO tags (id, title, user_id, color) VALUES('sfvbj8444', 'Ciphers', '324ddsf3', 'blue' );",
	"Tag 4 User 1":    "INSERT INTO tags (id, title, user_id, color) VALUES('fdfvsv555', 'General', '324ddsf3', 'green' );",
	"Tag 1 CN 1":      "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('325er3f573', 'ewrwerewercccvv333', 'CornellNote');",
	"Tag 4 CN 1":      "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('wtrferjsdg', '23rresfdf434r34r34', 'CornellNote');",
	"Tag 1 CN 2":      "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('325er3f573', '23rresfdf434r34r34', 'CornellNote');",
	"Tag 2 Note 3":    "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('wtrferjsdg', '12313c1ccc3223cd', 'Note' );",
	"Tag 3 Note 3":    "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('fdfvsv555', '12313c1ccc3223cd', 'Note' );",
}
