package db

//InsertSampleData ... stores sample data for DB
var InsertSampleData = map[string]string{
	"User 1":          "INSERT INTO users (id, user_name, email, password) VALUES('u324ddsf3', 'Steve', 'S@dfs.com' ,'testing');",
	"User 2":          "INSERT INTO users (id, user_name, email, password) VALUES('usfs34344', 'Emma Watson', 'ewat@ymail.co.uk' ,'password');",
	"User 3":          "INSERT INTO users (id, user_name, email, password) VALUES('usfsdf443', 'Ted Bundy', 'todiefor@mail.com', 'password');",
	"Folder 1":        "INSERT INTO folders (id, title, date_created, date_edited) VALUES('fwerwr433', 'Machine Learning', '2020-01-03', '2020-01-03');",
	"Folder 2":        "INSERT INTO folders (id, title, date_created, date_edited) VALUES('f434rsfg4', 'Cryptography', '2020-01-03', '2020-01-03');",
	"Folder 3":        "INSERT INTO folders (id, title, date_created, date_edited) VALUES('f3636566vv', 'Math Exploration', '2020-01-07', '2020-01-07');",
	"Folder 4":        "INSERT INTO folders (id, title, date_created, date_edited) VALUES('f43trfgf55g', 'Vue', '2020-01-06', '2020-01-06');",
	"Folder 5":        "INSERT INTO folders (id, title, date_created, date_edited) VALUES('ff54gtygt34', 'General', '2020-03-04', '2020-03-04');",
	"Folder 6":        "INSERT INTO folders (id, title, date_created, date_edited) VALUES('f8juyhtddg', 'Micro Biology', '2020-03-03', '2020-01-03');",
	"Folder 7":        "INSERT INTO folders (id, title, date_created, date_edited) VALUES('f7gbdbddfb', 'Astro Physics', '2020-03-03', '2020-01-03');",
	"Folder 1 User 1": "INSERT INTO folder_users (folder_id, user_id) VALUES('fwerwr433', 'u324ddsf3' );",
	"Folder 2 User 1": "INSERT INTO folder_users (folder_id, user_id) VALUES('f434rsfg4', 'u324ddsf3' );",
	"Folder 3 User 1": "INSERT INTO folder_users (folder_id, user_id) VALUES('f3636566vv', 'u324ddsf3' );",
	"Folder 4 User 1": "INSERT INTO folder_users (folder_id, user_id) VALUES('f43trfgf55g', 'u324ddsf3' );",
	"Folder 5 User 2": "INSERT INTO folder_users (folder_id, user_id) VALUES('f54gtygt34', 'usfs34344' );",
	"Folder 6 User 2": "INSERT INTO folder_users (folder_id, user_id) VALUES('f8juyhtddg', 'usfs34344' );",
	"Folder 7 User 2": "INSERT INTO folder_users (folder_id, user_id) VALUES('f7gbdbddfb', 'usfs34344' );",
	"folder_item1":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('fwerwr433', 'n12313c1ccc3223cd', 'Note' );",
	"folder_item2":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('f434rsfg4', 'n14234254533334cd',  'Note');",
	"folder_item3":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('f434rsfg4', 'cnewrwerewercccvv333',  'CornellNote');",
	"folder_item4":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('f434rsfg4', 'cn23rresfdf434r34r34',  'CornellNote');",
	"folder_item5":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('fwerwr433', 'cn43453453345345fffff', 'CornellNote' );",
	"folder_item6":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('f3636566vv', 'cn666tfdggdgdgfdfgdfgdf',  'CornellNote');",
	"folder_item7":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('f3636566vv', 'cn44dddddggdv545gg45gg',  'CornellNote');",
	"folder_item8":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('f3636566vv', 'cn2222325345gdfvgvtbtr',  'CornellNote');",
	"folder_item9":    "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('fwerwr433', 'cn8gbfbbybffdfdffddf', 'CornellNote' );",
	"folder_item10":   "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('f434rsfg4', 'cn9ufhgbdbdvddbgbdgbd',  'CornellNote');",
	"folder_item11":   "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('f3636566vv', 'n324242345wfdrcrc',  'Note');",
	"folder_item12":   "INSERT INTO folder_items (folder_id, item_id, item_type) VALUES('f434rsfg4', 'n7yrtfvvdvdvfdvdv',  'Note');",
	"Note 1":          "INSERT INTO notes (id, title, body, date_created, date_edited) VALUES('n12313c1ccc3223cd', 'Spyder', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex  non proident, sunt in culpa qui officia deserunt molli ' , '2020-03-03', '2020-01-03');",
	"Note 2":          "INSERT INTO notes (id, title, body, date_created, date_edited) VALUES('n14234254533334cd', 'Ciphers', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex  non proident, sunt in culpa qui officia deserunt molli ', '2020-03-05', '2020-01-05' );",
	"Note 3":          "INSERT INTO notes (id, title, body, date_created, date_edited) VALUES('n324242345wfdrcrc', 'Boolean Algebra', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex  non proident, sunt in culpa qui officia deserunt molli ', '2020-03-05', '2020-01-05' );",
	"Note 4":          "INSERT INTO notes (id, title, body, date_created, date_edited) VALUES('n7yrtfvvdvdvfdvdv', 'Encryption', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex  non proident, sunt in culpa qui officia deserunt molli ', '2020-03-05', '2020-01-05' );",
	"Note 1 User 1":   "INSERT INTO note_users (note_id, user_id ) VALUES('n12313c1ccc3223cd', 'u324ddsf3' );",
	"Note 2 User 1":   "INSERT INTO note_users (note_id, user_id ) VALUES('n14234254533334cd', 'u324ddsf3' );",
	"Note 3 User 1":   "INSERT INTO note_users (note_id, user_id ) VALUES('n324242345wfdrcrc', 'u324ddsf3' );",
	"Note 4 User 1":   "INSERT INTO note_users (note_id, user_id ) VALUES('n7yrtfvvdvdvfdvdv', 'u324ddsf3' );",
	"CornellNote 1":   "INSERT INTO cornell_notes (id, title, date_created, date_edited) VALUES('cnewrwerewercccvv333', 'Veniger Ciphers', '2020-03-03', '2020-01-03' );",
	"CornellNote 2":   "INSERT INTO cornell_notes (id, title, date_created, date_edited) VALUES('cn23rresfdf434r34r34', 'Casear Ciphers', '2020-03-03', '2020-01-03' );",
	"CornellNote 3":   "INSERT INTO cornell_notes (id, title, date_created, date_edited) VALUES('cn43453453345345fffff', 'Encryption', '2020-03-03', '2020-01-03' );",
	"CornellNote 4":   "INSERT INTO cornell_notes (id, title, date_created, date_edited) VALUES('cn666tfdggdgdgfdfgdfgdf', 'Logic Puzzels' , '2020-03-03', '2020-01-03');",
	"CornellNote 5":   "INSERT INTO cornell_notes (id, title, date_created, date_edited) VALUES('cn44dddddggdv545gg45gg', 'Infinity', '2020-03-03', '2020-01-03' );",
	"CornellNote 6":   "INSERT INTO cornell_notes (id, title, date_created, date_edited) VALUES('cn2222325345gdfvgvtbtr', 'Game Theory' , '2020-03-03', '2020-01-03');",
	"CornellNote 7":   "INSERT INTO cornell_notes (id, title, date_created, date_edited) VALUES('cn8gbfbbybffdfdffddf', 'Commands', '2020-03-03', '2020-01-03' );",
	"CornellNote 8":   "INSERT INTO cornell_notes (id, title, date_created, date_edited) VALUES('cn9ufhgbdbdvddbgbdgbd', 'Installation', '2020-03-03', '2020-01-03' );",
	"CN Cue 1":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('ccwerrtetgvcxd', 'cn23rresfdf434r34r34',  'What is the Vigenere Cipher', 'This scheme is based on using 26 Caeser ciphers with differing shifts of 0 - 25' );",
	"CN Cue 2":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('ccfgderrtreer', 'cnewrwerewercccvv333',  'What type of cipher is it', 'A polyalphabetical  substitution cipher');",
	"CN Cue 3":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('ccfdgdgdf343434', 'cnewrwerewercccvv333',  'More sample cuesss', 'that have more sample answers' );",
	"CN Cue 4":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('ccfdgdfge454', 'cnewrwerewercccvv333',  'CorMore sample cuesssnellNote', 'efv44 that eeee more sample answers' );",
	"CN Cue 5":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('cc2435ttgfsf', 'cn23rresfdf434r34r34',  'More sample cuesss', '3efdgvthat have more sample answers' );",
	"CN Cue 6":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('cc3544dgdgdd', 'cn23rresfdf434r34r34',  'More another on', 'dddf5 that have more sample answers' );",
	"CN Cue 7":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('ccfvvdfvftrf4', 'cn23rresfdf434r34r34',  'More another on', 'dddf5 that have more sample answers' );",
	"CN Cue 8":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('cc43fdvvfvbb5', 'cn43453453345345fffff',  'encryption 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex  non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. ' );",
	"CN Cue 9":        "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('ccsvdvt888888', 'cn43453453345345fffff',  'encryption 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem dolor sed viverra ipsum nunc aliquet. Netus et malesuada fames ac turpis egestas. at in tellus. Purus sit amuam. Magna fringilla urna porttitor rhoncus dolor ' );",
	"CN Cue 10":       "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('cc213edcscscs', 'cn43453453345345fffff',  'encryption 3', 'ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ' );",
	"CN Cue 11":       "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('cc554fdvdvdvdvdv', 'cn666tfdggdgdgfdfgdfgdf',  'Logic 1 ', 'dddf5 sadada sample sample sample niam, quis nostrud exercitation ullamco laboniam, quis nostrud exercitation ullamco laboniam, quis nostrud exercitation ullamco labo ple answers' );",
	"CN Cue 12":       "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('cc546ffvvfvvfv', 'cn666tfdggdgdgfdfgdfgdf',  'another puzzel', 'dddf5 tsample sample  answers' );",
	"CN Cue 13":       "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('cc4343ffrvvvv', 'cn2222325345gdfvgvtbtr',  'Dominant strategy', 'dddf5 that have more sample answers' );",
	"CN Cue 14":       "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('cc4353vvvvsvvv', 'cn8gbfbbybffdfdffddf',  'basic commands', 'dddf5 that have more sample answers' );",
	"CN Cue 15":       "INSERT INTO cornell_cues (id, cornell_note_id, cue, answer) VALUES('cc86867vsvdsvsv', 'cn9ufhgbdbdvddbgbdgbd',  'More another on', 'dddf5 that have more sample answers' );",
	"CN 1 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('cnewrwerewercccvv333', 'u324ddsf3' );",
	"CN 2 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('cn23rresfdf434r34r34', 'u324ddsf3' );",
	"CN 3 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('cn43453453345345fffff', 'u324ddsf3' );",
	"CN 4 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('cn666tfdggdgdgfdfgdfgdf', 'u324ddsf3' );",
	"CN 5 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('cn44dddddggdv545gg45gg', 'u324ddsf3' );",
	"CN 6 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('cn2222325345gdfvgvtbtr', 'u324ddsf3' );",
	"CN 7 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('cn8gbfbbybffdfdffddf', 'u324ddsf3' );",
	"CN 8 User 1":     "INSERT INTO cornell_users (cornell_note_id, user_id ) VALUES('cn9ufhgbdbdvddbgbdgbd', 'u324ddsf3' );",
	"Tag 1 User 1":    "INSERT INTO tags (id, title, user_id, color) VALUES('325er3f573', 'Definitions', 'u324ddsf3', 'red' );",
	"Tag 2 User 1":    "INSERT INTO tags (id, title, user_id, color) VALUES('wtrferjsdg', 'Security', 'u324ddsf3', 'orange' );",
	"Tag 3 User 1":    "INSERT INTO tags (id, title, user_id, color) VALUES('sfvbj8444', 'Ciphers', 'u324ddsf3', 'blue' );",
	"Tag 4 User 1":    "INSERT INTO tags (id, title, user_id, color) VALUES('fdfvsv555', 'General', 'u324ddsf3', 'green' );",
	"Tag 1 CN 1":      "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('325er3f573', 'cnewrwerewercccvv333', 'CornellNote');",
	"Tag 4 CN 1":      "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('wtrferjsdg', 'cn23rresfdf434r34r34', 'CornellNote');",
	"Tag 1 CN 2":      "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('325er3f573', 'cn23rresfdf434r34r34', 'CornellNote');",
	"Tag 2 Note 1":    "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('wtrferjsdg', 'n12313c1ccc3223cd', 'Note' );",
	"Tag 3 Note 1":    "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('fdfvsv555', 'n12313c1ccc3223cd', 'Note' );",
	"Tag 1 Note 3":    "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('325er3f573', 'n12313c1ccc3223cd', 'Note' );",
	"Tag 4 Note 3":    "INSERT INTO tag_items (tag_id, item_id, item_type) VALUES('fdfvsv555', 'n12313c1ccc3223cd', 'Note' );",
}
